name: Production Push/Pull

on:
  push:
    branches: [production]
  pull_request:
    branches: [production]

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint the project
        run: npm run lint
      - name: Run unit tests
        run: npm run test

  cypress-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: End-to-end using chrome
        uses: cypress-io/github-action@v4.2.0
        with:
          browser: chrome
          build: npm run build
          start: npm run preview
